import Ionicons from '@expo/vector-icons/Ionicons';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useCallback, useEffect, useRef, useState } from 'react';
import { ActivityIndicator, KeyboardAvoidingView, Platform, Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { IconButton } from '@/components/ui/IconButton';
import { Gradient } from '@/components/visual/Gradient';
import { colors } from '@/constants/colors';
import { platformOption } from '@/features/accounts/platforms';
import { intelligenceSession } from '@/features/intelligence/session';
import { askMediaNavigator, fetchAskHistory } from '@/features/intelligence/api';
import { EvidenceBlock, SupportingDataList } from '@/features/intelligence/components/Evidence';
import { describeIntelligenceError, SUGGESTED_QUESTIONS } from '@/features/intelligence/labels';
import { ApiError } from '@/lib/api/client';
import { formatRelativeTime } from '@/lib/format';
import { AskAnswer } from '@/types/api';

const MAX_QUESTION = 500;

function UserBubble({ text }: { text: string }) {
  return (
    <View className="mb-md max-w-[85%] self-end">
      <Gradient name="ai" style={{ borderRadius: 20, borderBottomRightRadius: 6, paddingHorizontal: 16, paddingVertical: 12 }}>
        <Text className="text-body text-white">{text}</Text>
      </Gradient>
    </View>
  );
}

function AssistantMark() {
  return (
    <Gradient name="ai" style={{ width: 24, height: 24, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }}>
      <Ionicons name="sparkles" size={13} color={colors.white} />
    </Gradient>
  );
}

function Answer({ answer, accountId, initiallyExpanded }: { answer: AskAnswer; accountId: string | null; initiallyExpanded: boolean }) {
  const [expanded, setExpanded] = useState(initiallyExpanded);
  return (
    <View className="mb-2xl">
      <UserBubble text={answer.question} />
      <View className="flex-row items-center">
        <AssistantMark />
        <Text className="ml-sm text-caption text-neutral-500">Media Navigator · {formatRelativeTime(answer.askedAt)}</Text>
      </View>
      {!answer.answerable ? (
        <Text className="mt-xs text-caption font-semibold text-warning">Your synced data can’t fully answer this</Text>
      ) : null}
      <Text className="mt-sm text-body text-navy">{answer.directAnswer}</Text>

      <Pressable
        onPress={() => setExpanded(!expanded)}
        accessibilityRole="button"
        accessibilityState={{ expanded }}
        className="mt-xs min-h-11 flex-row items-center self-start"
      >
        <Text className="text-label font-semibold text-primary">{expanded ? 'Hide analysis' : 'Show analysis & evidence'}</Text>
        <Ionicons name={expanded ? 'chevron-up' : 'chevron-down'} size={16} color={colors.primary} style={{ marginLeft: 4 }} />
      </Pressable>

      {expanded ? (
        <View className="mt-md">
          {answer.observation ? (
            <EvidenceBlock title="Observation" kind="aiSummary">
              {answer.observation}
            </EvidenceBlock>
          ) : null}
          <EvidenceBlock title="Supporting data" kind="observed">
            <SupportingDataList data={answer.supportingData} accountId={accountId} />
          </EvidenceBlock>
          {answer.explanation ? (
            <EvidenceBlock title="Possible explanation" kind="aiHypothesis">
              {answer.explanation}
            </EvidenceBlock>
          ) : null}
          {answer.recommendation ? (
            <EvidenceBlock title="Recommendation" kind="aiSuggestion">
              {answer.recommendation}
            </EvidenceBlock>
          ) : null}
          {answer.expectedMeasurement ? (
            <EvidenceBlock title="What to measure next" kind="aiSuggestion">
              {answer.expectedMeasurement}
            </EvidenceBlock>
          ) : null}
        </View>
      ) : null}
    </View>
  );
}

/** Assistant screen: answers are generated by the server from this account's synced data. */
export default function AskScreen() {
  const router = useRouter();
  const params = useLocalSearchParams<{ accountId?: string; q?: string }>();
  const accountId = params.accountId || null;
  const platformName = platformOption((accountId && intelligenceSession.overview(accountId)?.account.platform) || 'instagram').name;
  const scrollRef = useRef<ScrollView>(null);

  const [history, setHistory] = useState<AskAnswer[]>([]);
  const [historyState, setHistoryState] = useState<'loading' | 'ready' | 'error'>('loading');
  const [aiConfigured, setAiConfigured] = useState(true);
  const [input, setInput] = useState('');
  const [pending, setPending] = useState<string | null>(null);
  const [error, setError] = useState<{ title: string; message: string } | null>(null);
  const [latestId, setLatestId] = useState<string | null>(null);
  const autoAsked = useRef(false);
  // Scroll to the newest message only when the conversation grows, not when an answer is expanded.
  const scrollOnNextLayout = useRef(true);

  useEffect(() => {
    fetchAskHistory(accountId)
      .then((result) => {
        setHistory(result.history);
        setAiConfigured(result.aiConfigured);
        scrollOnNextLayout.current = true;
        setHistoryState('ready');
      })
      .catch(() => setHistoryState('error'));
  }, [accountId]);

  const ask = useCallback(
    async (raw: string) => {
      const question = raw.trim();
      if (question.length < 3 || pending) return;
      setError(null);
      scrollOnNextLayout.current = true;
      setPending(question);
      setInput('');
      try {
        const answer = await askMediaNavigator(accountId, question);
        setHistory((current) => [answer, ...current.filter((a) => a.id !== answer.id)]);
        setLatestId(answer.id);
        scrollOnNextLayout.current = true;
      } catch (e) {
        setInput(question); // keep the question so the user can retry
        const code = e instanceof ApiError ? e.code : undefined;
        const copy = describeIntelligenceError(code, e instanceof Error ? e.message : 'Unable to answer right now.');
        setError({ title: copy.title, message: copy.message });
      } finally {
        setPending(null);
      }
    },
    [accountId, pending],
  );

  // A suggestion tapped on the Intelligence home is asked right away.
  useEffect(() => {
    if (historyState === 'ready' && params.q && !autoAsked.current && aiConfigured) {
      autoAsked.current = true;
      void ask(params.q);
    }
  }, [historyState, params.q, aiConfigured, ask]);

  // Oldest first, newest at the bottom, like a conversation.
  const conversation = [...history].reverse();
  const canSend = input.trim().length >= 3 && !pending && aiConfigured;

  return (
    <SafeAreaView edges={['top', 'left', 'right', 'bottom']} style={{ flex: 1, backgroundColor: colors.white }}>
      <View className="flex-row items-center border-b border-neutral-100 px-sm pb-sm">
        <IconButton icon="chevron-back" accessibilityLabel="Back" onPress={() => router.back()} />
        <Gradient name="ai" style={{ width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center', marginLeft: 4 }}>
          <Ionicons name="sparkles" size={18} color={colors.white} />
        </Gradient>
        <View className="ml-md flex-1">
          <Text className="text-title text-navy" accessibilityRole="header">
            Ask Media Navigator
          </Text>
          <Text className="text-caption text-neutral-500">Answers use only your synced {platformName} data</Text>
        </View>
      </View>

      <KeyboardAvoidingView className="flex-1" behavior={Platform.OS === 'ios' ? 'padding' : 'height'}>
        <ScrollView
          ref={scrollRef}
          className="flex-1"
          contentContainerClassName="px-xl pb-lg pt-lg"
          keyboardShouldPersistTaps="handled"
          onContentSizeChange={() => {
            if (!scrollOnNextLayout.current) return;
            scrollOnNextLayout.current = false;
            scrollRef.current?.scrollToEnd({ animated: true });
          }}
        >
          {historyState === 'loading' ? <ActivityIndicator color={colors.primary} /> : null}
          {historyState === 'error' ? <Text className="mb-lg text-caption text-neutral-500">Recent questions couldn’t be loaded.</Text> : null}

          {historyState !== 'loading' && conversation.length === 0 && !pending ? (
            <View className="mb-xl">
              <Text className="text-display text-navy">What would you like to know?</Text>
              <Text className="mt-xs text-body text-neutral-500">
                Ask about your posts, formats and engagement. If your data can’t answer something, Media Navigator will say so.
              </Text>
              {aiConfigured ? (
                <View className="mt-lg">
                  {SUGGESTED_QUESTIONS.map((question) => (
                    <Pressable
                      key={question}
                      onPress={() => void ask(question)}
                      accessibilityRole="button"
                      accessibilityLabel={`Ask: ${question}`}
                      className="mb-sm min-h-12 flex-row items-center rounded-2xl bg-violet-light px-lg active:opacity-80"
                    >
                      <Ionicons name="sparkles-outline" size={16} color={colors.violet} />
                      <Text className="ml-md flex-1 text-body text-navy">{question}</Text>
                    </Pressable>
                  ))}
                </View>
              ) : null}
            </View>
          ) : null}

          {conversation.length > 0 ? <Text className="mb-lg text-caption font-semibold uppercase tracking-wide text-neutral-500">Recent questions</Text> : null}
          {conversation.map((answer) => (
            <Answer key={answer.id} answer={answer} accountId={accountId} initiallyExpanded={answer.id === latestId} />
          ))}

          {pending ? (
            <View className="mb-xl">
              <UserBubble text={pending} />
              <View className="flex-row items-center" accessibilityRole="progressbar" accessibilityLabel={`Analyzing your ${platformName} data`}>
                <ActivityIndicator color={colors.primary} size="small" />
                <Text className="ml-sm text-label font-normal text-neutral-500">Analyzing your {platformName} data…</Text>
              </View>
            </View>
          ) : null}

          {error ? (
            <View className="mb-lg rounded-lg bg-danger-light p-lg" accessibilityRole="alert">
              <Text className="text-label font-semibold text-danger">{error.title}</Text>
              <Text className="mt-xs text-caption text-neutral-500">{error.message}</Text>
            </View>
          ) : null}
        </ScrollView>

        <View className="border-t border-neutral-100 px-lg py-sm">
          {!aiConfigured ? (
            <Text className="py-md text-center text-label font-normal text-neutral-500">AI analysis is temporarily unavailable.</Text>
          ) : (
            <View className="flex-row items-end">
              <TextInput
                value={input}
                onChangeText={setInput}
                placeholder="Ask something…"
                placeholderTextColor={colors.placeholder}
                multiline
                maxLength={MAX_QUESTION}
                accessibilityLabel="Your question"
                className="mr-sm max-h-32 min-h-12 flex-1 rounded-xl bg-neutral-50 px-lg py-md text-body text-navy"
                editable={!pending}
              />
              <Pressable
                onPress={() => void ask(input)}
                disabled={!canSend}
                accessibilityRole="button"
                accessibilityLabel="Send question"
                accessibilityState={{ disabled: !canSend }}
                className="h-12 w-12 overflow-hidden rounded-full"
              >
                <Gradient name="ai" style={{ flex: 1, alignItems: 'center', justifyContent: 'center', opacity: canSend ? 1 : 0.35 }}>
                  <Ionicons name="arrow-up" size={22} color={colors.white} />
                </Gradient>
              </Pressable>
            </View>
          )}
        </View>
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
}
