-- Migration 0001: authentication schema (users, profiles, sessions).
-- Schema only. This migration inserts no rows.
--
-- Conventions:
--   * Primary keys are random UUIDv4 strings generated by the Worker (crypto.randomUUID()).
--   * Timestamps are INTEGER milliseconds since the Unix epoch (UTC).
--   * D1 enforces foreign keys.

CREATE TABLE users (
  id            TEXT    PRIMARY KEY NOT NULL,
  -- Stored normalized: trimmed and lower-cased by the Worker.
  email         TEXT    NOT NULL,
  -- Self-describing hash string: "pbkdf2-sha256$<iterations>$<salt>$<hash>". Never plaintext.
  password_hash TEXT    NOT NULL,
  created_at    INTEGER NOT NULL,
  updated_at    INTEGER NOT NULL,
  CHECK (email = lower(trim(email)) AND length(email) BETWEEN 3 AND 254),
  CHECK (password_hash LIKE 'pbkdf2-sha256$%')
);

CREATE UNIQUE INDEX users_email_unique ON users (email);

CREATE TABLE profiles (
  id           TEXT    PRIMARY KEY NOT NULL,
  user_id      TEXT    NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  display_name TEXT    NOT NULL,
  -- Key of an R2 object in MEDIA_BUCKET; NULL until the user uploads an avatar.
  avatar_key   TEXT,
  created_at   INTEGER NOT NULL,
  updated_at   INTEGER NOT NULL,
  CHECK (length(display_name) BETWEEN 1 AND 80)
);

-- One profile per user.
CREATE UNIQUE INDEX profiles_user_id_unique ON profiles (user_id);

CREATE TABLE sessions (
  id           TEXT    PRIMARY KEY NOT NULL,
  user_id      TEXT    NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  -- Hex SHA-256 digest of the session token. The token itself is never stored.
  token_hash   TEXT    NOT NULL,
  expires_at   INTEGER NOT NULL,
  created_at   INTEGER NOT NULL,
  last_used_at INTEGER NOT NULL,
  -- NULL while active; set when the session is revoked (logout).
  revoked_at   INTEGER,
  CHECK (length(token_hash) = 64),
  CHECK (expires_at > created_at)
);

CREATE UNIQUE INDEX sessions_token_hash_unique ON sessions (token_hash);
CREATE INDEX sessions_user_id_idx ON sessions (user_id);
CREATE INDEX sessions_expires_at_idx ON sessions (expires_at);
