-- Migration 0002: connected accounts schema.
-- Schema only. This migration inserts no rows.
--
-- Conventions:
--   * Primary keys are random UUIDv4 strings generated by the Worker (crypto.randomUUID()).
--   * Timestamps are INTEGER milliseconds since the Unix epoch (UTC).
--   * D1 enforces foreign keys.

CREATE TABLE connected_accounts (
  id                  TEXT    PRIMARY KEY NOT NULL,
  user_id             TEXT    NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  platform            TEXT    NOT NULL,
  platform_account_id TEXT    NOT NULL,
  account_name        TEXT,
  account_username    TEXT    NOT NULL,
  status              TEXT    NOT NULL CHECK (status IN ('connected', 'reauthorization_required', 'error')),
  token_reference     TEXT    NOT NULL,
  token_expires_at    INTEGER,
  created_at          INTEGER NOT NULL,
  updated_at          INTEGER NOT NULL,
  last_synced_at      INTEGER,
  CHECK (platform IN ('instagram', 'youtube', 'linkedin', 'facebook'))
);

CREATE UNIQUE INDEX connected_accounts_user_platform_account_unique ON connected_accounts (user_id, platform, platform_account_id);
CREATE UNIQUE INDEX connected_accounts_token_reference_unique ON connected_accounts (token_reference);
CREATE INDEX connected_accounts_user_id_idx ON connected_accounts (user_id);
